verbose: false
concurrency: <%= Integer(ENV.fetch("SIDEKIQ_CONCURRENCY", 10)) %>
pidfile: ./tmp/pids/sidekiq.pid
logfile: ./log/sidekiq.log
queues:
  - critical
  - mailers
  - default
  - searchkick
  - active_storage_analysis
  - active_storage_purge
  - low
production:
  concurrency: <%= Integer(ENV.fetch("SIDEKIQ_CONCURRENCY", 5)) %>
staging:
  concurrency: <%= Integer(ENV.fetch("SIDEKIQ_CONCURRENCY", 15)) %>

:schedule:
  DispatchBroadcastWorker:
    cron: "0 * * * * *" # Runs every minute
    include_metadata: true
    description: "This worker dispatch broadcast that was enqueued"
    enabled: true

  DispatchScenarioEventWorker:
    cron: "0 * * * * *" # Runs every minute
    include_metadata: true
    description: "This worker dispatch scenario event that was enqueued"
    enabled: true

  DispatchReminderEventWorker:
    cron: "0 * * * * *" # Runs every minute
    include_metadata: true
    description: "This worker dispatch reminder event that was enqueued"
    enabled: true
  
  DispatchRichmenuWorker:
    cron: "0 0 * * * *" # Run every hour
    include_metadata: true
    description: "This worker dispatch rich menu to friends"
    enabled: true

  GetNumberOfMessageDeliveryWorker:
    cron: "0 0 5 * * *" # Runs every day
    include_metadata: true
    description: "This worker retrieve insight data using line api"
    enabled: true

  DailySyncFriendsWorker:
    cron: "0 0 3 * * *" # Runs every day
    include_metadata: true
    description: "This worker sync friends information for all account"
    enabled: true

  MonthlyInsightAnalyzerWorker:
    cron: "0 0 6 * * *" # Runs every day
    include_metadata: true
    description: "This worker analyze quota consumption"
    enabled: true

  GetQuotaWorker:
    cron: "0 0 2 * * *" # Runs every day
    include_metadata: true
    description: "This worker get quota of accounts every day"
    enabled: true

  GetQuotaConsumptionWorker:
    cron: "0 * * * * *" # Runs every minute
    include_metadata: true
    description: "This worker get quota consumption of accounts"
    enabled: true

  SidekiqHealthCheckWorker:
    cron: "0 * * * * *" # Runs every minute
    include_metadata: true
    description: "This worker notifies slack when sidekiq queue or errors look unhealthy"
    enabled: true
